canal.id=1
canal.ip=
canal.register.ip=
canal.port=11111
canal.metrics.pull.port=11112
canal.zkServers=
canal.withoutNetty=false
canal.serverMode=rocketMQ
canal.destinations=hmdp
canal.auto.scan=false
canal.auto.scan.interval=5

canal.instance.global.mode=spring
canal.instance.global.lazy=false
canal.instance.global.spring.xml=classpath:spring/file-instance.xml

canal.mq.canalBatchSize=50
canal.mq.canalGetTimeout=100
canal.mq.flatMessage=true
canal.mq.accessChannel=local
canal.mq.database.hash=true
canal.mq.send.thread.size=30
canal.mq.build.thread.size=8

rocketmq.producer.group=hmdp-canal-producer
rocketmq.enable.message.trace=false
rocketmq.customized.trace.topic=
rocketmq.namespace=
rocketmq.namesrv.addr=study-agent-rocketmq-namesrv:9876
rocketmq.retry.times.when.send.failed=3
rocketmq.vip.channel.enabled=false
